### ISSUE TITLE
Replacing all <U+0E4D> + <U+0E32> code points with <U+0E33> code point

### ISSUE THREAD

**Issue by bact** [stopwords-iso/stopwords-th#2]
## Background

In Thai language, we can combine 

ํ U+0E4D THAI CHARACTER NIKHAHIT
and
า U+0E32 THAI CHARACTER SARA AA

to produce

ำ U+0E33 THAI CHARACTER SARA AM

However, U+0E33 (Sara Am) is the standard way for input and data processing.

## Issue

Current stopword list contains this wrong combinations:

41: ทํา
42: ทําให้
48: นํา
69: สําหรับ

(all using U+0E4D follows with U+0E32)

## Fix proposed

Change them to

41: ทำ
42: ทำให้
48: นำ
69: สำหรับ

(all using U+0E33)

----
reported by Korakot Chaovavanich 
from https://www.facebook.com/groups/408004796247683/permalink/511357762579052/?comment_id=511415055906656

**Comment by genediazjr** [comment]
Closed by #3

**Comment by genediazjr** [comment]
Closed by #3
